### ISSUE TITLE
Upgrade this repo to work with Starcounter 2.4

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#1]
The `master` branch of this repo should support Starcounter 2.4 only.

Please add the missing configuration for that in `csproj` and `packages.config`

**Comment by PatrykSzwer** [comment]
Done, closing.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Blending/releases/tag/5.0.0
- published in the App Warehouse
