### ISSUE TITLE
Some tests are failing on master branch build

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#106]
https://teamcity.starcounter.org/viewLog.html?buildId=48883&buildTypeId=Apps_Blending_BlendingMasterWithStarcounterDevelop24

There is a test that seems to be flaky or just failing. Please investigate.

**Comment by kegor** [comment]
Closed because fixes were merged in #119.

**Comment by PatrykSzwer** [comment]
Reopening since there are still some flaky tests: https://teamcity.starcounter.org/viewLog.html?buildId=49813&tab=buildResultsDiv&buildTypeId=Apps_Blending_BlendingMasterWithStarcounterDevelop24

**Comment by PatrykSzwer** [comment]
Seems like updating selenium libraries in TC fixed flakiness. I'll close this issue for now, since there is no discovered flaky tests anymore.

**Comment by kegor** [comment]
I see errors on `master` branch in BE tests: https://teamcity.starcounter.org/viewLog.html?buildId=50862.
I think changes from this commit could fix the problem: https://github.com/Starcounter/Blending/commit/16c9f3ad73ed0abee10ecc561beb90c93b2551c0.

@warpech what do you think?

**Comment by kegor** [comment]
Closed again, because merged changes in #151 makes sense.
