### ISSUE TITLE
CSS variable collection selected in layout doesn't work for uniform classes

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#111]
### Steps to reproduce
1. Create new CSS variables collection with variable --uni-danger.
2. Set this collection for topbarLayout
3. Refresh page.
### Expected result
Delete button on the bottom should change color.
![image](https://user-images.githubusercontent.com/25042256/37089353-8d7b4f28-2200-11e8-97fd-0510795b4dc6.png)

### Actual result
Button is not affected:
![image](https://user-images.githubusercontent.com/25042256/37089386-a2779026-2200-11e8-8465-497a20c4a520.png)

**Comment by warpech** [comment]
@PatrykSzwer is this still valid?

**Comment by warpech** [comment]
Closing as finished in PR #64
