### ISSUE TITLE
Area item URI combo box should contain URIs from all apps

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#116]
### Expected result

Area item URI combo box should be prepopulated with available view URIs from all currently running apps.

### Actual result

It is prepopulated only from view URIs from the current app (BlendingEditor)

![image](https://user-images.githubusercontent.com/566463/37193364-c7b2f776-2369-11e8-830c-f18f81ea1a8b.png)

**Comment by PatrykSzwer** [comment]
Closing as done.
