### ISSUE TITLE
Implement partial matching of HTTP headers

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#118]
### Expected result

As a user of BlendingEditor, I would like to define an HTTP header rule for a layout condition using partial string matching of an HTTP header. 

Let's discuss what would be better? Partial string matching rules like (begins with, contains, ends with) or regexp? I think regexp might be too slow for such usage.

### Actual result

Right now the HTTP header value is matched exactly against the stored value (case insensitive).

### Screenshot

![image](https://user-images.githubusercontent.com/566463/37205398-eefb492a-2394-11e8-80e5-1dbcabb76078.png)

**Comment by PatrykSzwer** [comment]
Closing as done.
