### ISSUE TITLE
Reduce the number of default layouts, add area items and layout conditions to predefined layouts from a template

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#121]
### Expected result

As a user of BlendingEditor, I would like to be able to use predefined layouts from template to recreate the layouts that BlendingEditor creates in an empty database.

The expected predefined layouts from a template are: `Single point` layout, `Topbar` layout, `Sidebar` layout (merge with current `Responsive` layout), `HolyGrail` layout, `Login` layout (data includes Layouts, Areas, Area items, Layout conditions)

The expected default layouts are: `Topbar` layout, `Login` layout (data includes Layouts, Areas, Area items, Layout conditions)

### Actual result

The current predefined layouts from a template are: `Single point` layout, `Topbar` layout, `Sidebar` layout, `HolyGrail` layout (data includes only Layouts and Areas; NOT Area items and Layout conditions)

The current default layouts are: `Topbar` layout, `Login` layout, `Sidebar` layout, `Responsive` layout, `HolyGrail` layout (data includes Layouts, Areas, Area items, Layout conditions)

I have a preliminary fix for that, but it will need more work.

**Comment by warpech** [comment]
Fix is tracked in PR #122

**Comment by PatrykSzwer** [comment]
Closing as done.
