### ISSUE TITLE
Exception in Areas Preview iframe after creating Area with the empty name.

### ISSUE THREAD

**Issue by kegor** [Starcounter/Blending#136]
### Steps to reproduce
1. Create new Empty Layout.
2. Go to the 'Areas'.
3. Click 'New area'.
4. Click 'Save' (without changing any inputs).
5. Go to the 'General'.

### Expected result
There are no errors in Preview iframe.

### Actual result
There is an exception:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Starcounter.Json.set_Item(String key, Object value) in C:\TeamCity\BuildAgent\work\sc-15723\Level1\src\Starcounter.XSON\Class Json\Json.cs:line 497
```

##### Starcounter version 
2.4.0.5313

##### Involved apps' version
 - BlendingEditor@6.0.0
 - BlendingProvider@6.0.0
 
##### Browsers affected
- [x] Chrome
- [x] Firefox

### Screenshot
![image](https://user-images.githubusercontent.com/17431807/37649141-fa5b430a-2c41-11e8-8b87-796a4caeb09b.png)

**Comment by PatrykSzwer** [comment]
It's caused by generatingAreaPreview for the newly created area.

**Comment by kegor** [comment]
Closed, because fix was merged in #153.

**Comment by PatrykSzwer** [comment]
I'm not sure if this solution is correct. I think we should keep consistency in BE app, and it shouldn't be possible to save empty area entity. I think it should work the same as e.g adding and saving empty header for layout condition:
![rep](https://user-images.githubusercontent.com/25042256/38498620-4b82d7fc-3c05-11e8-8690-ad3da15eb420.gif)

It should automatically delete empty item during saving.

**Comment by warpech** [comment]
Good point, can you make an issue for that? I think this should be solved using server-side validation.

**Comment by PatrykSzwer** [comment]
> Good point, can you make an issue for that? I think this should be solved using server-side validation.

Done: #168
