### ISSUE TITLE
Divide the docs

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#138]
Currently, the only end-user documentation about BlendingEditor is in https://github.com/Starcounter/Blending/blob/master/README.md. This file is a mix of information for:

1. solution owners - end user description of BlendingEditor GUI and administrative URLs
2. developers - API description of how to plug in to use BlendingProvider features, such as DisplayAppTitle

We should divide such information to more specialized files in the `docs/` folder, such as:

- `docs/administration.md` - administrative URLs such as `/blendingeditor/cleardata`
- `docs/gui.md` - BlendingEditor GUI:
   - layouts, areas, area items
   - layout conditions
   - CSS variable management
   - composition editor
- `docs/displayapptitle.md` - information for developers who want to use display app title feature in their apps
- `docs/blendingprovider.md` - information about things that are in the scope of BlendingProvider. This page will be short, because it will be just a list of things with external links about what they are

Information from README.md about the subset and superset composition matching should be moved to the Docs page https://docs.starcounter.io/v/2.4/topic-guides/blendable-web-apps/view-composing

**Comment by mmnosek** [comment]
I highly support this idea! This would make documentation clearer and easier to follow. The more I think about documentation and the more competitors/similar solutions I check, the more I like this. 

Moreover, this should be a general approach in Starcounter documentation (not for blending, specifically). Developing single app/APIs is one thing, setting up a whole solution is another. One of the examples is Odoo, where docs for app developers and "solution owners" are separated.

**Comment by PatrykSzwer** [comment]
Closing as done.
