### ISSUE TITLE
Signing in requires manual page refresh

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Blending#139]
### Steps to reproduce
1. Run `BlendingEditor`
1. Run `SignIn`
1. Open `/BlendingEditor`
1. SignIn with some user

### Expected result
Layout group page should be visible

### Actual result
"Access denied" is visible

##### Starcounter version 
Starcounter-Develop-2.4.0.5497

##### Involved apps' version
* StarcounterApps/Blending@21cecf559285fabd62244251bfeb307f35bbf45a
* StarcounterApps/SignIn@16c9f3ad73ed0abee10ecc561beb90c93b2551c0

**Comment by PatrykSzwer** [comment]
Closing as done. (huurrrayy) 🎆
