### ISSUE TITLE
"Use view keeper" setting isn't exported to configuration dump

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Blending#140]
### Steps to reproduce
1. Uncheck "Use view keeper" in the configuration (by default it's checked)
1. Export data
1. Check "Use view keeper"
1. Import data
1. Refresh

### Expected result
"Use view keeper" checkbox shouldn't be checked

### Actual result
"Use view keeper" checkbox is checked, meaning it was not imported or exported

**Comment by kegor** [comment]
For me Import even is not starting:
![image](https://user-images.githubusercontent.com/17431807/38131825-26ef7c7a-3411-11e8-9220-b151350aacfd.png)
I will investigate this.

**Comment by kegor** [comment]
I found the solution for the problem above (changing `as` on `is`), but the whole fix has the problem related to this case:
https://github.com/Starcounter/Blending/issues/140
![image](https://user-images.githubusercontent.com/17431807/38237513-135e179e-3730-11e8-8433-0d16893e8b22.png)

**Comment by kegor** [comment]
Closing because related changes were merged in the #253.
