### ISSUE TITLE
Add "Reset to defaults" button in settings

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Blending#142]
When I install `BlendingEditor` for the first time, I have some default layouts that look very nice. After playing around, I would like to be able to reset everything to the initial (post-installation) state. Currently, if I delete all layouts and compositions, I am stuck. 

Red "Reset to defaults" button should:
* delete layouts (same operation as red delete all button)
* delete compositions
* reset "use view keeper" setting
* create the same objects as on app installation (or first run, actually)
* be secured by modal, with appropriate warning message

**Comment by kegor** [comment]
Closed because the fix was merged in #158.
