### ISSUE TITLE
Layout detail pages improvements

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Blending#144]
In layout details page of `BlendingEditor` we have 3 subpages:

**General**: *BlendingEditor/layout/X/general*
![blendingeditor_and_windows_10_and_timesheet_-_michal_nosek_march_2018](https://user-images.githubusercontent.com/4943949/37775817-38c39c48-2de4-11e8-85ce-1b68ccbabce2.png)
* Padding above is to big

**Areas**: *BlendingEditor/layout/X/areas*
* Title should be change from "Layout - LayoutName" to "Areas - LayoutName"
* Description is missing (would be neat to have some description what is an area in the blue box like at conditions page"

**Layout conditions**: *BlendingEditor/layout/X/layoutconditions*
* Title should be consistent with previous pages, so: "Conditions - LayoutName"
* Menu item should be shorter: "Conditions" instead if "Layout conditions"

**Comment by kegor** [comment]
Closed because all possible and related changes were merged in #144.
