### ISSUE TITLE
In blending editor, enabled means disabled

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Blending#145]
The label on the screenshot below should be "Disabled". Checking checkbox means actually that condition is disabled.

![blendingeditor](https://user-images.githubusercontent.com/4943949/37780346-e52ffd46-2dee-11e8-882e-66f7514ed674.png)

**Comment by kegor** [comment]
For me it also looked like a bug, it's good that now we have a confirmed work item for this.

**Comment by kegor** [comment]
Closed because the fix was merged in the #150.
