### ISSUE TITLE
Open Composition Editor in a new window

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Blending#146]
Having `CompositionEditor` above the website is very inconvenient because:
* it takes space on my screen and makes the actual application smaller
* sometimes if there are some full-screen-size elements with `z-index` it's hard to use it at all
* editor is small, so in a little bit more complex compositions working with this is quite hard

I wanted to edit this:
![blendingeditor_and_windows_10](https://user-images.githubusercontent.com/4943949/37829071-e736c5f2-2e9d-11e8-8cba-2e4421c3743c.png)

And I end up with this:
![blendingeditor](https://user-images.githubusercontent.com/4943949/37829132-23cae8f4-2e9e-11e8-9aff-9c2b9b0a3001.png)

I think we should move it to the additional window, if possible. 

@warpech @tomalec WDYT? Low prio.

**Comment by alshakero** [comment]
PR in #205
