### ISSUE TITLE
Wrong Launchpad background color

### ISSUE THREAD

**Issue by mmnosek** [Starcounter/Blending#148]
### Steps to reproduce
* Install `Launchpad` and `BlendingEditor`
* Go to `/blendingeditor`
* Click in the left top corner to see the actual launchpad

### Expected result
It looks neat

### Actual result
It doesn't look neat. We're on the dark side 😛 

### Technical information
It looks like composition that is applied on application startup (`Topbar`) defines this background to be `#333`. All apps provide black icons, so it looks bad. I think this background should be white and apps names black. It's this line: https://github.com/Starcounter/Blending/blob/0953b8fe7ea93942e3f49174f57f0bd4faa24e23/src/BlendingEditor/Website/Content/HtmlCompositions/topbar-composition.html#L74

##### Involved apps' version
StarcounterApps/Blending@16c9f3ad73ed0abee10ecc561beb90c93b2551c0
StarcounterApps/Launchpad@cf87472 

### Screenshot
![blendingeditor](https://user-images.githubusercontent.com/4943949/37844420-032078a6-2ec8-11e8-8690-bffde9f0ee5e.png)

**Comment by warpech** [comment]
A solution to this is to force the SVG icons to have a different color (white) using CSS.

**Comment by PatrykSzwer** [comment]
Closing as done.
