### ISSUE TITLE
Decorating surface blending points

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#15]
_Issue moved from Website repository: https://github.com/Starcounter/Website/issues/303_

After https://github.com/Starcounter/RebelsLounge/issues/232

This proposal is intended as a step to make the GUI of BlendingEditor more powerful and the experience configuring the typical blending configurations more "point and click".

For the app responses that are placed in the blending points of a surface, there is commonly a need to do something more than just direct insertion of these responses to `starcounter-include`. It might be additional behavior or some specific look-and-feel:

i. highlight link to the current page using a CSS class ([issue](https://github.com/Starcounter/RebelsLounge/issues/53#issuecomment-262828532))
ii. autofocus the first form field, if no other element is explicitly focused ([issue](https://github.com/StarcounterApps/SignIn/issues/49))
ii. wrap responses in an expandable dropdown icon ([custom element in surface Shadow DOM](https://github.com/Starcounter/Website/blob/3ffdb91ab4d201e225d2d84d5d39e01e887b4077/src/WebsiteEditor/Content/HtmlCompositions/topbar-composition.html))

These things cannot really be part of the composition because we want them in all compositions inserted in a particular blending point.

In this proposal, I will call the above behaviors "decorating the blending point of a surface".

My goal is to make it user-friendly to apply such decorations by having:

1. built-in decorations that can be applied by point and click in the GUI
2. a page in docs that explains the pattern of writing own decorations in form of custom elements, similar to `<topbar-menu>` [here](https://github.com/Starcounter/Website/blob/3ffdb91ab4d201e225d2d84d5d39e01e887b4077/src/WebsiteEditor/Content/HtmlCompositions/topbar-composition.html).

To implement point 1, the built-in decorations would be implemented in one (modular) custom element that listens to the `stamped` event:

```js
{
  BlendingPoints: {
    TopLeft: {
      /* app responses go here */
      Launchpad: {..},
      BlendingProvider: {..}
   },
  },
  BlendingDecorations: {
    TopLeft: [
      {Name: "HighlightCurrentLink", Enabled: false, Config: []},
      {Name: "AutofocusFirstInput", Enabled: false, Config: []},
      {Name: "WrapInDropdown", Enabled: true, Config: [{Key: "icon", Value: "hamburger"}, {Key: "label", Value: "Menu"}]}
    ]
  }
}
```

```html
<template>
  <template is="dom-bind">
    <starcounter-include 
      view-model="{{model.BlendingPoints.TopLeft}}" 
      blending-decorations="{{model.BlendingDecorations.TopLeft}}" //this is not really a property of starcounter-include but metadata for blendingprovider-decorations
      slot="Website/topleft">
    </starcounter-include>
  </template>

  <template is="declarative-shadow-dom">
    <blendingprovider-decorations>
      <slot name="Website/topleft"></slot>
    </blendingprovider-decorations>
  </template>
</template>
```

This will allow us to have a GUI in BlendingEditor [that might look like this](https://docs.google.com/drawings/d/1H4DZwuPp9gP9MO-2kOPR6_C_Pw4VQxP5zDcQFfA8_LI/edit)

@tomalec WDYT?

-------

Edit: made the text clearer. [Old version](https://gist.github.com/warpech/90d1548582fc5125def69318476292dc)

**Comment by warpech** [comment]
@tomalec proposes that it should better be done without GUI, just using custom elements in Shadow DOM.

I agree that a mature low-level implementation is better before we ever attempt doing a GUI.

I have started a provisional directory of relevant custom elements here: https://github.com/Starcounter/Blending/wiki

**Comment by warpech** [comment]
The wiki was created. Closing in favor or https://github.com/Starcounter/RebelsLounge/issues/246
