### ISSUE TITLE
Buttons for Layout types are not placed in the selection window

### ISSUE THREAD

**Issue by kegor** [Starcounter/Blending#156]
### Steps to reproduce
1. Open BlendingEditor.
2. Click "New layout".
3. Make window width less than 915px.

### Expected result
Buttons after decreasing window width go to the next row.

### Actual result
Buttons are not placed in the selection window.

##### Starcounter version 
2.4.0.5502

##### Involved apps' version

BlendingEditor@6.0.0
 
##### Browsers affected

- [x] Chrome
- [x] Firefox

### Screenshot
![image](https://user-images.githubusercontent.com/17431807/38079357-5dfee61c-3347-11e8-9227-752611444c88.png)

**Comment by PatrykSzwer** [comment]
@alshakero I think this one should be low hanging fruit for you.
