### ISSUE TITLE
Add button to close the editor

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#18]
_Issue moved from CompositionEditor repository: https://github.com/Starcounter/CompositionEditor/issues/3_

Basically, all programs and pop-ups have a way to close the window by clicking on a close button in the top right or top left corner. It would thus be intuitive to add a simple button that does this to the editor.

**Comment by warpech** [comment]
Today we made a decision to:

- add a "Close" button at the right the "Save" button
- clicking on "Close" should cancel pending changes and close the composition editor panel
- remove the "Cancel" button

**Comment by tomalec** [comment]
Could you give a reason why revert (without closing) feature was removed?

Also, closing without reverting (as it was before available with key shortcut) - personally I find it useful for fiddling and debugging, but maybe that's not a common case.

**Comment by warpech** [comment]
Revert without closing is considered an anti-pattern. 

It is sometimes implemented using a `<input type="reset">`, but most users have a problem understanding what it does and are likely to remove their work by mistake. Criticism of reset button:

- opinion by Jacob Nielsen, the god of web usability: https://www.nngroup.com/articles/reset-and-cancel-buttons/
- more arguments: https://ux.stackexchange.com/questions/93671/do-we-really-require-a-reset-button-for-form-fields

If you think about it, can you name one piece of popular software that has a feature to revert without closing?

**Comment by tomalec** [comment]
I'd say we should rather compare not to form features but rather file editing features (like in IDE or visual tool). But, I get the point of that even there is rarely revert button and it may be more confusing that just close and reopen.

Speaking of closing without reverting, WGYT about "minimize" kind of button?

**Comment by warpech** [comment]
> Speaking of closing without reverting, WGYT about "minimize" kind of button?

I think that a need for this will not be high when we can open the editor in a separate window: https://github.com/Starcounter/Blending/issues/146

**Comment by kegor** [comment]
Closed because all needed changes were merged into related repositories.
