### ISSUE TITLE
[Mapping branch] Import feature does not work

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#181]
Leftover from https://github.com/Starcounter/RebelsLounge/issues/240.

@kegor wrote:

Import data on `Settings` page is not working with exception.

**Comment by warpech** [comment]
@kegor wrote:

after [I added](https://github.com/Starcounter/Blending/commit/bfebe6eb132afc1e6871b36a5c06920f28669ad8) `--mapping-mode=true` flags into `unload/reload` StarDump commands I see this error message:
```
 Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unexpected value 'true' for option 'mapping-mode'
 at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
 at StarDump.CommandLineInterface.Execute(String[] args) in C:\TeamCity\BuildAgent\work\sc-17110\StarDump\src\StarDump\CommandLineInterface.cs:line 36
 
 C:\Program Files\Starcounter\StarDump>
```
Starcounter version: 2.4.990.71
@miyconst, could you please clarify: I'm using mapping Starcounter with the old StarDump version? @habib535 said that you could help with this question.

**Comment by warpech** [comment]
@miyconst wrote:

>Regarding the last issue from the list above, after [I added](https://github.com/Starcounter/Blending/commit/bfebe6eb132afc1e6871b36a5c06920f28669ad8) `--mapping-mode=true` flags into `unload/reload` StarDump commands I see this error message:

The flag does not need any value, just add it as `--mapping-mode`.

**Comment by warpech** [comment]
@kegor wrote:

@miyconst, thank you for this clarification, without `=true`:
1. Export is working well.
2. Import says:
![image](https://user-images.githubusercontent.com/17431807/39121779-4d81d426-46fb-11e8-99cf-85b0d36c8b54.png)
I think we need that `--skipschema` because without it I'm getting:
![image](https://user-images.githubusercontent.com/17431807/39121899-c36c4ed2-46fb-11e8-9745-f1160e23f2bd.png)
So seems like we could omit activity with fixing Export/Import in Mapped BlendingEditor for a while?

**Comment by warpech** [comment]
@miyconst wrote:

[How to reload with `--skip-schema` and `--mapping-mode`](https://github.com/Starcounter/StarDump/issues/118).

**Comment by PatrykSzwer** [comment]
I spoke with @miyconst and he said that this feature will probably not be obtainable with the mapping feature. We have to think about other possibilities what to do with it.

**Comment by miyconst** [comment]
The explanation of why it's not possible is provided in the issue - https://github.com/Starcounter/StarDump/issues/118.

**Comment by PatrykSzwer** [comment]
Closing since it was done by https://github.com/Starcounter/Blending/pull/212 and then in https://github.com/Starcounter/Blending/pull/233
