### ISSUE TITLE
ViewKeeper should use imported-template instead of starcounter-include

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#190]
Current implementation of ViewKeeper creates issues when It's used along with compositions.

Related comments: https://github.com/Starcounter/Blending/issues/30#issuecomment-369301653
https://github.com/Starcounter/Blending/pull/189#issue-186611609

**Comment by tomalec** [comment]
I'd appreciate somebody more familiar with ViewKeeper implementation would correct me if I'm wrong.

After reading https://github.com/Starcounter/Blending/blob/master/docs/gui.md#view-keeper and basic skimming through the code, I suppose, `ViewKeeper` replaces the merged view that is to be inserted into blending point and wraps it. 

It means any multiple siblings should get wrapped as well, `BlendingProvider_` is also wrapped, so composition for merged view is there.

Therefore there should be no need to cover siblings of view keeper, plus it does not make much sense to put a composition around viewkeeper view.


However, the developer who creates an HTML Insertion point does not know whether the view will get hijacked by view keeper or not
therefore he/she uses `<starcounter-include>`,
so there is not much we can change to `imported-template`.

**Comment by tomalec** [comment]
Thank you @un-tone for the review.
I think we should not change this to `imported-template`, but I found a reason to reconsider the way ViewKeeper is implemented https://github.com/Starcounter/Blending/issues/192

**Comment by tomalec** [comment]
I'm closing as "won't fix" (that way), as we need to figure out another way to solve #30
