### ISSUE TITLE
Change the text "Click here" to "Double-click here" in the editor input placeholder

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#21]
_Issue moved from CompositionEditor repository: https://github.com/Starcounter/CompositionEditor/issues/6_

**Comment by tomalec** [comment]
Why? After one click you are able to provide selector, after two click you are able to pick one from the list. I think we should change the UX not just label.

**Comment by warpech** [comment]
Because when you see the input, it is obvious that you can click on it, but it is not obvious that you can double click.

I agree that the UI should be changed, but this idea was a 5 minute UX improvement.

**Comment by PatrykSzwer** [comment]
Closing as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Blending/releases/tag/5.2.0
- published in the App Warehouse
