### ISSUE TITLE
Composition editor is not working for holyGrailLayout

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#230]
### Steps to reproduce
1. Call /resetdata
2. Create new layout based on Holy grail template.
3. Go to Conditions tab.
4. Remove empty "any URI" condition for topbarLayout and replace it with similar for holy grail layout.
5. Refresh the page, open composition Editor and try to select starcounter-include.
### Expected result
List is populated
### Actual result
Exception in console:
![image](https://user-images.githubusercontent.com/25042256/40854076-7cdf2338-65d0-11e8-9fa5-214ca33aeec8.png)

@alshakero could u take a look at this?

**Comment by alshakero** [comment]
Should be fixed in https://github.com/Starcounter/starcounter-layout-html-editor/pull/37. If you copy and paste the PR's contents to your local `sys/starcounter-layout-html-editor` you could test.
