### ISSUE TITLE
After changing Deleted field value to the true, the entity completely removing from the database.

### ISSUE THREAD

**Issue by kegor** [Starcounter/Blending#235]
### Steps to reproduce
1. Start `MappingWorkspace`.
2. Create `userAdmin`, make `SignIn`, open `BlendingEditor`.
3. Create new [empty] `Layout`.
4. Open newly created `Layout`, click `Delete` button.

### Expected result
Layout still in the database, but Deleted field value equal to `true`.

### Actual result
Layout not existing in the database.

##### Starcounter version 
2.4.990.86

##### Involved apps' version
![image](https://user-images.githubusercontent.com/17431807/41031987-d16ac444-698a-11e8-8692-3e1c1c34d187.png)

##### Browsers affected
- [x] Chrome
- [x] Firefox

#### Notes
⚠️ Last time when I could make pull&push in the `MappingWorkspace` repo was 26.04.2018, so this is true that code which I'm running is perhaps a bit old.

**Comment by kegor** [comment]
I need to add that I reproduced this behaviour not only for `WebTemplate` but also for `WebSection`, so I can assume that it is applicable for an arbitrary entity with `Deleted` field.
@mtornwall, I think that root cause might be somewhere in the `MappingWorkspace` because in our `Blending`s `master` branch "Deleted" entities are always staying in the database. Could you please clarify this point a little?

**Comment by mtornwall** [comment]
@kegor Which branch of MappingWorkspace?

**Comment by kegor** [comment]
Hi @mtornwall, `blending` branch.

**Comment by mtornwall** [comment]
https://github.com/Starcounter/MappingWorkspace/blob/blending/src/GenerateMappers/BlendingEditor/WebTemplate.cpp#L49-L51

As can be seen here: if the `Deleted` flag is set on the root entity, `Refresh()` returns `false`, which explains the behavior you are seeing. Usually, when you have a table that has a `Deleted` property, you would not check for `root.Deleted` in `Refresh()`. See e.g.:

https://github.com/Starcounter/MappingWorkspace/blob/blending/src/GenerateMappers/People/Person.cpp#L44-L56

**Comment by kegor** [comment]
@mtornwall, thank you for the answer, I tried to remove this check https://github.com/Starcounter/MappingWorkspace/blob/blending/src/GenerateMappers/BlendingEditor/WebTemplate.cpp#L49-L51 and entity was not completely removed after clicking on Delete button.
