### ISSUE TITLE
Release a version that contains import/export

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#237]
Since https://github.com/Starcounter/Blending/pull/212 was merged to `master`, is there something preventing us from making a release?

Release a version that contains import/export for Starcounter 2.4.

**Comment by PatrykSzwer** [comment]
Before releasing I would like to add one more part to import/export feature, which is migrating also CSS variable collections. After that I can do the release.

**Comment by PatrykSzwer** [comment]
Closing as done.
