### ISSUE TITLE
Retro-review of #20

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Blending#26]
As `compositioneditor-panel` is a Polymer element, I'd stick to their docs and use `connectedCallback() { super.connectedCallback(); /* ... */}` 

- https://meowni.ca/posts/polymer-2-cheatsheet/#lifecycle-methods
- https://www.polymer-project.org/2.0/docs/devguide/custom-elements#element-lifecycle

**Comment by PatrykSzwer** [comment]
Actually, after adding `super.connectedCallback();` line, I'm getting a syntax error:
`Uncaught SyntaxError: 'super' keyword unexpected here`

**Comment by tomalec** [comment]
That's because element is created using Polymer 1 syntax https://github.com/Starcounter/Blending/blob/b7fa4f758b773c5b5301559c5d4bf9b977b9025e/src/BlendingEditor/wwwroot/BlendingEditor/elements/compositioneditor-panel/compositioneditor-panel.html#L48

I'd change it to complete 2.0 
```js
    customElements.define('compositioneditor-panel', class extends Polymer.Element{});
```

**Comment by warpech** [comment]
This is a hybrid element, so the Polymer 1 syntax applies to it. What you should be using is `attached` callback. See: https://www.polymer-project.org/1.0/docs/devguide/registering-elements

Migrating from one version of an API to another is not productive. Both versions work equally well.

**Comment by PatrykSzwer** [comment]
Please take a look on #49

**Comment by PatrykSzwer** [comment]
Closing as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Blending/releases/tag/5.2.0
- published in the App Warehouse
