### ISSUE TITLE
Attach URI dropdown does not include handlers defined with SelfOnly = true

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#275]
### Steps to reproduce

1. Delete the local db to make sure that it is empty
2. Start all apps in Omni
3. Go to http://localhost:8080/useradmin to create the admin user
4. Log in as the admin user and go to `/BlendingEditor`
5. Go to TopbarLayout > Areas 
6. Click on "Items" next to TopbarRight. There will be one item already
7. Expand the "Attach URI" dropdown

### Expected result

In the dropdown, I should see all blended views that are defined in `blend.json` coming from all apps that participate in Omni.

For example, three URIs coming from https://github.com/Starcounter/ShoppingCart/blob/48bafedf70cf8c0e4eb034c04cec5130ea4ac709/src/ShoppingCart/blend.json

I think this is because they are `SelfOnly = true`: https://github.com/Starcounter/ShoppingCart/blob/a5839c5056183f21b8c36723b1c0b4a54eab6582/src/ShoppingCart/Api/Handlers.cs#L83

### Actual result

These URIs are present in Network tab of Administrator, but not in the dropdown in Blending Editor

##### Involved apps' version

HeadsOmni 50085e535433045543fc62406f6e00a55f4c3d0b
 
### Screenshot

![dropdown](https://user-images.githubusercontent.com/566463/43835636-eb9271aa-9b12-11e8-947c-c52f0d158134.png)

@kegor can you pls check if this is a bug in Level1. If yes, pls make an issue for @alemoi

**Comment by kegor** [comment]
For the moment I can't start `ShoppingCart` after `UserAdmin.Mapper` and `SignIn.Mapper` with the following error:
```
C:\gitc\ShoppingCart>run
ShoppingCart -> default (starting application .)                                                                        
[23:25:13, Starcounter (default)]
Starcounter.DbException: ScErrFailingEntrypoint (SCERR4259): The user code entrypoint method raised an exception. System.MissingMethodException: Method not found: 'Microsoft.Extensions.DependencyInjection.IServiceCollection Starcounter.Startup.Routing.RouterServiceCollectionExtensions.AddRouter(Microsoft.Extensions.DependencyInjection.IServiceCollection)'.
   at ShoppingCart.Startup.ConfigureServices(IServiceCollection services)
   at Starcounter.Startup.DefaultStarcounterBootstrapper.Start(IStartup application)
   at ShoppingCart.Program.Main() in C:\gitc\ShoppingCart\src\ShoppingCart\Program.cs:line 9
   at Starcounter.Hosting.Package.ExecuteEntryPoint(Application application, Assembly assembly) in C:\  c_work\sc-19252\Level1\src\Starcounter.Hosting\Hosting\Package.cs:line 553
Version: 2.4.990.127.
```
@habib535 met same problem with other apps, and problem might be in the Authorization library.

**Comment by habib535** [comment]
@kegor please change all the values of `"Starcounter.Startup"` from `0.3.0` to `0.4.0` in `packages.config` in whole solution.
In Package manager console execute `update-package -reinstall`

I am thinking about how to identify this problem in the build solution.

**Comment by kegor** [comment]
I eventually ran `ShoppingCart`/`SignIn.Mapper`/`UserAdmin.Mapper`/`Blending.Mapper` projects separately after rebuild for each and now from the HeadsOmni solution folder.
Then I found that `blend.json` presented in the `C:\gitc\ShoppingCart\src\ShoppingCart\bin\Debug` but not presented in the `C:\gitc\HeadsOmni\src\ShoppingCart\src\ShoppingCart\bin\Debug`.

Alexey pointed on the documentation https://docs.starcounter.io/v/2.4/topic-guides/blendable-web-apps/view-model-attaching#separate-attachment-rules-in-json which clarifies main points for the actual solution:
1. `blend.json` should have `Copy if newer` as value for the `Copy to Output Directory` property.
2. If the project is plan to be run on the mapping build of the Starcounter, `blend.json` should contain only `Uri`, `FullclassName` and `Contexts` properties.

After I performed these actions for the `ShoppingCart` project in the HeadsOmni solution and re-run I got the following result:
![image](https://user-images.githubusercontent.com/17431807/44678995-6db5e200-aa42-11e8-9a0c-848675ccce0c.png)

As the complex solution, I could suggest to make similar actions for each project in the HeadsOmni solution and bump its version.

@warpech do you agree with this way?

**Comment by warpech** [comment]
Yes, so it means that the bug that I reported is incorrect. The problem was just in file `blend.json` not being copied to `bin/debug`.

I have made a new issue: https://github.com/Starcounter/HeadsOmni/issues/263

Thanks for the investigation!
