### ISSUE TITLE
I cannot change the relevant layout condition of an area item

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#278]
### Steps to reproduce

1. Load the configuration of Omni project in BlendingEditor (https://github.com/Starcounter/HeadsOmni/tree/63efecd0db0b442fb0dea0fb25decd32668c80c8/config)
2. Click on KioskCheckoutLayout
3. Click on Area Items
4. Expand the "Items" button near the "Top Left" area item
5. In the layout condition select `/(shoppingcart|orders).*`
6. Press save

### Expected result

The new layout condition should be saved as the selection for this area item

### Actual result

The "Save" button does not become active after the layout condition is selected

I can cheat that by clicking on the `Disabled` checkbox twice. Then I can save, but still, it does not have any effect to change the saved layout condition.

##### Starcounter version 2.4.990.122

Screen recording: https://drive.google.com/open?id=1C11TJZQ1Z5UBVDqZ2E8Kynd-muye5jP0

**Comment by kegor** [comment]
Closing because related PR https://github.com/Starcounter/Blending/pull/279 was merged.
