### ISSUE TITLE
Remove v0 warning from `compositioneditor-panel`

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Blending#28]
`compositioneditor-panel` still checks for Shadow DOM v0 environment, to show the warning. We no longer support v0, so it won't happen. Therefore, we should remove this warning.

**Comment by kegor** [comment]
Closing as done in PR #32.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Blending/releases/tag/5.2.0
- published in the App Warehouse
