### ISSUE TITLE
After deleting a layout, the export file is broken

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#280]
### Steps to reproduce

1. Create a layout with layout conditions and areas
2. Set some area items that are relevant for a particular layout condition
2. Also make a custom composition for that layout
3. Delete that layout
4. Export the settings
5. Clear the database
6. Import the settings

### Expected result

It should import ok

### Actual result

The import fails with the message: `Sequence contains no elements`

**Comment by PatrykSzwer** [comment]
Closing as done.
