### ISSUE TITLE
Two fallen BlendingEditor tests in the TC.

### ISSUE THREAD

**Issue by kegor** [Starcounter/Blending#287]
Reported by Urban:
Failing Blending TeamCity build: https://teamcity.starcounter.org/viewLog.html?buildId=68173&tab=buildResultsDiv&buildTypeId=Apps_Blending_BlendingMasterWithStarcounterDevelop24

The only change was some changes in package.bat, which that build doesn't use. https://github.com/Starcounter/Blending/commit/440f6aa8161c8108419fef153af5fc37b647339f

**Comment by warpech** [comment]
Fixed in PR https://github.com/Starcounter/Blending/pull/313
