### ISSUE TITLE
Upgrade juicy-select to the current version

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#29]
Upgrade `juicy-select` with Bower to the current version https://github.com/Juicy/juicy-select/releases/tag/1.1.0

**Comment by kegor** [comment]
Closing as done in PR #39.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Blending/releases/tag/5.2.0
- published in the App Warehouse
