### ISSUE TITLE
Replace Area's default checkbox with plain text "yes" | "no" 

### ISSUE THREAD

**Issue by alshakero** [Starcounter/Blending#294]
The checkbox implies user interaction. And it threw @warpech and I off. I suggest turning this into a simple text of "yes" and "no". 

![image](https://user-images.githubusercontent.com/17054134/46081384-ac9f9a80-c19c-11e8-8503-8d615b3e78dc.png)

**Comment by PatrykSzwer** [comment]
Closing as done.
