### ISSUE TITLE
Composition should be automatically saved the same way as Notepad++ does

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Blending#297]
I find myself losing my changes in the BlendingEditor rather often.

It would be very nice to get the changes automatically saved in "dirty" mode the same way as Notepad++ does.

**Comment by warpech** [comment]
Closing as too complex. There is no precedence of a Starcounter app saving work in progress automatically, and I'd rather not create it here.

Recently, BlendingEditor started to support editing custom compositions through files, so you can use the autosave feature of Notepad++ now.

If anything, maybe we could implement "autosaves" similarly how they are done in WordPress: https://codex.wordpress.org/Revisions#Autosaves

> There is only ever a maximum of one autosave per user for any given post. New autosaves overwrite old autosaves. This means that no, your tables do not grow by one row every 60 seconds. In multi-user settings, one autosave is stored for each user.

> Autosaves are enabled for all posts and pages but do not overwrite published content. Autosaves are stored as a special type of revision; they do not overwrite the actual post. In fact, whether your power goes out, your browser crashes, or you lose your internet connection, when you go back to edit that post, WP will toss up a warning telling you that it has a backup of your post and a link to restore the backup. When reviewing revisions, autosaves are clearly marked. 

But that means, we would need to store the autosave in a separate file, which, again, I find too complex to bother at this stage of maturity.
