### ISSUE TITLE
Save and serve compositions from file system not from database

### ISSUE THREAD

**Issue by miyconst** [Starcounter/Blending#301]
Currently the blending compositions are saved and distributed through database. It makes it very inconvenient due to:

- Impossible to use any kind of IDE, such as Visual Studio, Visual Studio Code, Notepad++ for editing the compositions.
- Re-creating database resets the compositions.
- Impossible to track versioning of the compositions. It's possible to export compositions into a JSON file, and commit it, but it produces one huge un-formatted file with all blending information in it.
- No easy way to share specified compositions between developers/databases/hosts.
- No easy way to remove/reset certain compositions.
- No easy way to implement and distribute default compositions per app, but outside of the app's HTML views.

That is why I propose to keep and serve the HTML compositions from file system, rather than from the database. Every composition should be presented as a separate file, and the files should be structured into folders for easier navigation and search.

cc @warpech, @tomalec

**Comment by tomalec** [comment]
I totally support above. I also believe the place of HTML is in the HTML file and HTML-in-JSON or HTML-in-C#.

We already discussed it a bit, having the ideas to serve custom compositions from `htmlmerger` so it would be even cleaner for our client-side platform to use it.

Adding HTML compositions to the merged partials would also give use de-duping/performance improvement for free (at least as long as HTML Imports or equivalent will be there)

AFAIR we started to keep **custom** compositions in the DB, as we consider them changeable but our customers, therefore part of customization. Needless to mention legacy from keeping JSON configuration for `juicy-tile-list` or `flexbox-layouts` ;) 👴 .We also planed to have more advanced composition management, versioning, rolling back, iterations between handcrafted ones, and build with machine support (AI blending).

Also as a food for thought before the meeting, I'd like to bring the idea that was also emerging quite often: treating views as data.

I believe none of the above ideas and goals collide. 
We need to find a way to just join them without overcomplicating.

I think we could just introduce convention to keep custom compositions in FS, which could then be fed to DB if needed.

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/Blending/issues/302#issuecomment-426809057

**Comment by warpech** [comment]
We agreed that we will serve compositions from the file system. This allows us the solution owner to install composition dependencies using a package manager.

The compositions will be served from the BlendingProvider's runtime directory.

**Comment by mmnosek** [comment]
We learned that it's hard to work with compositions in Omni project. Please keep in mind that we should make it possible to work on compositions simultaneously. Right now it's a nightmare due to uncomparable `.json` files.

**Comment by miyconst** [comment]
@warpech please remember to update the README as well.

**Comment by warpech** [comment]
I am not still satisfied with the solution even though PR #320 is now merged and used in HeadsOmni.

Current problem: compositions are present as HTML files, but snapshots of them are still used in `blendingeditor.json`. Because of that, there is still problem with conflicts in JSON when merging changes.

Solution proposed by @mmnosek:

1. Make storing custom compositions in files mandatory, not optional as it is now
2. Remove `Html` property completely from JSON export file
3. Change internal references in JSON export file from ObjectIDs to something deterministic, such as natural numbers or GUIDs.

I will work on that next week.

**Comment by alshakero** [comment]
Wholeheartedly agree with @warpech's and @mmnosek's proposals.

**Comment by alshakero** [comment]
Sorry closed by mistake.

**Comment by warpech** [comment]
Point 3 of my comment is implemented in https://github.com/Starcounter/Blending/pull/326

**Comment by warpech** [comment]
Point 2 and 4 of my comment is implemented in https://github.com/Starcounter/Blending/pull/329

**Comment by warpech** [comment]
Point 2 of my comment is implemented in https://github.com/Starcounter/Blending/pull/331

**Comment by warpech** [comment]
Points 2, 3 and 4 are currently released. Point 1 is moved to a separate issue (https://github.com/Starcounter/Blending/issues/335), should not affect HeadsOmni for now.
