### ISSUE TITLE
Too many changes between import and export files

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#302]
When you import a JSON configuration and then export JSON to a file, the input and output files should be mostly (or exactly the same).

Currently it is not the case. For Heads Omni configuration, there are  2305 insertions(+), 1369 deletions(-)!

I can see the following problems:

- the order of the data in the output file seems to be different (reversed?) than the order in the input file
- there are many GUIDs which are regenerated for export. @PatrykSzwer why do we need such GUIDs? Couldn't you use object IDs instead of GUIDs generated on the fly?

This makes it hard to reviews PRs like https://github.com/Starcounter/HeadsOmni/pull/435

![2018-10-03 12_37_45-sourcetree](https://user-images.githubusercontent.com/566463/46405812-bb8ccc80-c709-11e8-8083-d9454d420a50.png)

**Comment by tomalec** [comment]
Speaking of just files, I'd like to reduce number of introduces names, concepts custom elements etc.

WDYT, about:

`<composition-body>`->`<template is="declarative-shadow-dom" presentation="custom">` -> `<template is="shadow-root" presentation="custom">`


All ids to `<template is="shadow-root" presentation="custom" partial-id="value-you-see-in-markup-on-real-page">`

**Comment by tomalec** [comment]
Fair point, but that way you need more boilerplate, than copy'n'pasted code from regular view, also with such approach, we could just concatenate it with `/sc/htmlmerger` as is. And `<template>` gives us inertness and guarantees that regardless of parser `<scripts>` will not be executed before needed etc.

**Comment by PatrykSzwer** [comment]
>I think we should create a seperate file for each entry in HtmlViewCompositions array. 

We can think about it, but right now I don't think we have time and resources to take care of that. 
Right now I'm waiting for @kegor to add mapped GUIDs to the proper database classes to minimize amount of differences between exported files.

**Comment by kegor** [comment]
I added `Guid` in `AttachmentRule`:
1. In `Blending`: https://github.com/Starcounter/Blending/commit/8aaac6ad6c6ce66c4b42c529f21689221d91fd71
2. In `Blending.Mapper`: https://github.com/Starcounter/Blending.Mapper/commit/efda8a4d264c4e0d2247593ad99a999a0c4311fd
3. In `DoctorM`: https://github.com/Starcounter/DoctorM/commit/56fc5c044e40981d50831e19f9fc0891988054e5

It works perfect (expected the same attachement rules in export file) in case when before the import I only remove compositions.

If I make `Remove all` (through the remove layouts button), I see 32 additional new rules after import (and in export file then) to the existing 52 after the first run. This is result for only 5 apps running: `BlendingEditor`, `BlendingProvider`, `M`, `SignIn` and `UserAdmin`. I'm working on explanation.

**Comment by PatrykSzwer** [comment]
I currently can't run `Blending` app branch with your changes. I'm receiving: 
In console:
```
Starcounter.DbException: ScErrDatabaseEngineTerminated (SCERR10007): The server detected that the user code host executable (sccode.exe) unexpectedly terminated during a management operation. , PID=8816, Database=default
Version: 2.4.990.168.
Help page: https://docs.starcounter.io/?q=SCERR10007.
   at Starcounter.Server.Commands.StartExecutableCommandProcessor.<>c__DisplayClass4_0.<Execute>b__3(CommandTask task) in C:\   c_work\sc-19489\Level1\src\Server\Starcounter.Server\Commands\Processors\StartExecutableCommandProcessor.cs:line 178
   at Starcounter.Server.Commands.CommandProcessor.<>c__DisplayClass68_0.<WithinTask>b__0(CommandTask t) in C:\ c_work\sc-19489\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 487
   at Starcounter.Server.Commands.CommandProcessor.WithinTask(CommandTask task, Func`2 func) in C:\     c_work\sc-19489\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 515
   at Starcounter.Server.Commands.CommandProcessor.ProcessCommand(NotifyCommandStatusChangedCallback notifyStatusChangedCallback) in C:\        c_work\sc-19489\Level1\src\Server\Starcounter.Server\Commands\CommandProcessor.cs:line 301
ErrorCode=10007
HResult=-2146233088
HelpLink=https://docs.starcounter.io/?q=SCERR10007
---> Starcounter.DbException: ScErrProcessExitCodeNotAvailable (SCERR10040): The exit code of the terminating process was not available.
Version: 2.4.990.168.
Help page: https://docs.starcounter.io/?q=SCERR10040.
ErrorCode=10040
HResult=-2146233088
HelpLink=https://docs.starcounter.io/?q=SCERR10040
```

In mapping debug tool:
```
[8816] sc_abort() being called: sc_request_create(type_id, nullptr, 0, &ref) failed with error 15020.
[8816] sc_abort(): sc_request_create(type_id, nullptr, 0, &ref)
```

Any1 of you also have problems like that?

@wanderlust-ginge maybe you will know something about those error.

**Comment by mtornwall** [comment]
@PatrykSzwer 

> C:\Users\Martin>scperror 15020
ScErrMappingInconsistent (SCERR15020): The operation cannot be executed because at least one mapping is in an inconsistent state.

## Fastest solution
Delete database.

## Better solution
Figure out which mappings are inconsistent:

```
SELECT Inferior.Name, Consistent FROM Starcounter.Internal.Metadata.Mapping
```

Apps where `Consistent == false` need to reinitialize their virtual databases. Try starting them individually until all are consistent.

**Comment by PatrykSzwer** [comment]
Closing as done.
