### ISSUE TITLE
Failling TC tests

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/Blending#308]
https://teamcity.starcounter.org/viewLog.html?buildId=72148&tab=buildResultsDiv&buildTypeId=Apps_Blending_BlendingMasterWithStarcounterDevelop24 (built it 3 times in a row, same result)

Failing tests
```
LayoutGroupsPageTest(Chrome).LayoutGroupsPage_AddLayout
LayoutGroupsPageTest(Firefox).LayoutGroupsPage_AddLayout
```

@warpech @kegor I do not know who to assign.

**Comment by warpech** [comment]
Closing as a duplicate of https://github.com/Starcounter/Blending/issues/287
