### ISSUE TITLE
The currentpage doesn't refresh after signing in

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Blending#321]
### Steps to reproduce
1. Run BlendingEditor with BlendingProvider, SignIn and omni composition
1. Use the widget in top-right corner to sign in
1. notice the main area doesn't reload or show that you're now signed in. SignIn should explain you're signed in, though.
1. Reload the page, you can use BE. Sign out using button in top-right - notice that now the main area reloads

### Expected result

in step 3. the main area should reload with newly accessible content

**Comment by PatrykSzwer** [comment]
Fixed in #370. Closing.
