### ISSUE TITLE
Show/hide button UX

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Blending#344]
I would like to discuss the behavior of show/hide button.

Consider each selected element could be one of the following:
 - **visible** - `window.getComputedStyles(element).display !== 'none'` (please note, that it does not necessarily that user can see it (fully) on the screen - other CSS rules may hide it, like `visibility`, `height: 0`, etc. ), 
 - **non-visible** - `window.getComputedStyles(element).display === 'none'`, 
 - **hidden** - _non-visible_ in result of our action, 
 - **shown** - _visible_ in result of our action,
 - **n/a** - `TextNode, Comment, ...`

Set of selected elements, naturally can contain any combination of above.

My questions are:
1. Should we have just one button, always enabled, and will not indicate the state of selected elements that just toggles the state?
   -   _visible_ -> hidden -> _visible_
   - _non-visible_ -> shown -> _non-visible_
  For example, if you select _visible_ A, _non-visible_ B, _n/a_ C, it will change it to _non-visible_ A, _visible_ B, _n/a_ C
2. Should we have two buttons: show and hide. Each will switch from respectively _non-visible_ to _shown_ and _visible_ to _hidden_? Button will be disabled if there are no elements to transform, therefore it will indicate somehow the state of elements
3. Show "show" button just `display: unset` to restore browser-defined layout (`display: table`, etc.), or do more force full `display: block` to avoid scenarios, when element is not stylable, as it is collapsed table/link or whatever else?
4. Should we add new/ replace global top button with per-element display button?
5. Should we disallow multiple selection, and do not bother about it?
6. Should we disable global hide button when multiple elements are selected?

The overall idea is not to require the user to understand HTML and CSS to do basic things.

@warpech, @alshakero WDYT?

**Comment by warpech** [comment]
@tomalec can this be closed? We will implement show/hide in the simple editor by the use of `hidden` attribute, which is tracked in https://github.com/Starcounter/Blending/issues/149#issuecomment-442868722.

If you disagree pls reopen.
