### ISSUE TITLE
Make the tree-view and Ace panes resizable (horizontally) and collapsible

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Blending#345]
It would be great to have horizontally draggable, separator between panes - so user could adjust the space he/she needs to editors.
Or to focus even more on single editor to completely collapse the other one to a side.

@alshakero Could you take it?

**Comment by warpech** [comment]
Closing as no further work will happen on this, since the tree view was removed in https://github.com/Starcounter/Blending/pull/367
