### ISSUE TITLE
Improve UX of selecting a partial view

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Blending#347]
This is a finding of @mmnosek from https://github.com/Starcounter/HeadsOmni/issues/269

### Steps to reproduce
1. Open any HeadsOmni page,
2. Open composition editor,
3. Try to find a partial you are interested in
   - Browse the list manually,
   - write part of a file name in (CSS selector) field, hoping for fuzzy search

### Expected result
Should be easy to pick a partial you are interested in

### Actual result
It's easy to miss the partial even that it's on the list.
Bold identifier is not descriptive and confusing, grayed one which contains URL that @mmnosek was looking for is hard to catch. 

Partial picker that allows just to click on partial could be better.
 

### Browsers affected
n/a

**Comment by warpech** [comment]
Closing as this is tracked partially in the following issues:

- Composition editor starcounter-include dropdown should allow to filter by View URI (#286)
- Floating toolbar to pick blending point for composition editing (https://github.com/Starcounter/Blending/issues/22)
