### ISSUE TITLE
Remove the right "Visual editor" from default UI

### ISSUE THREAD

**Issue by alshakero** [Starcounter/Blending#352]
Remove the right side "Visual editor". It gets in the way really and isn't helpful at least to me. I don't think this is something that we can change someone's mind about. It's one of the things where "I just don't like it" is a good argument. Maybe we need to vote. Also, now when you uncheck it out, the ace-editor doesn't know the window was resized, so it keeps wrapping the code early (before reaching full width). You need to resize the whole window to trigger recalcuation. 

Moved from https://github.com/Starcounter/starcounter-layout-html-editor/issues/44

**Comment by PatrykSzwer** [comment]
@alshakero lets do the first, easy step that we agreed already and then move to hardest tasks. Please hide visual editor by default in the composition editor window.
