### ISSUE TITLE
Palindrom-redirect stopped working

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#47]
### Steps to reproduce
1. Go to `blendingeditor/surfacegroups`.
2. Create a new surface or select existing one.
3. Click `Delete` button inside general view.
### Expected result
User is redirected back to surfacegroups page.
### Actual result
Nothing is happening. That includes errors in console and exceptions.

**Comment by PatrykSzwer** [comment]
Closing as done.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Blending/releases/tag/5.2.0
- published in the App Warehouse
