### ISSUE TITLE
🤸 Add CSS variable presets

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#51]
Right now, CSS variable management starts with an empty list of variables.

It would be great if we could prepopulate the list of variables by either:

1. detecting the currently registered CSS variables
2. listing known CSS variables that come from Underwear.css

Depends on https://github.com/Starcounter/Blending/pull/48 and https://github.com/Starcounter/Blending/issues/50

**Comment by PatrykSzwer** [comment]
Closing as done.
