### ISSUE TITLE
Add themability of Paper and Vaadin components

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#52]
After https://github.com/Starcounter/Blending/issues/51 is done, see if we can go any further by allowing to theme Paper and Vaadin web components.

**Comment by warpech** [comment]
Depends on https://github.com/Starcounter/RebelsLounge/issues/258.

This issue will be about adding some UI or preconfiguration for it.

**Comment by PatrykSzwer** [comment]
Closing as done in #199

**Comment by warpech** [comment]
Note to future self. This feature will be removed. See: https://github.com/Starcounter/Blending/issues/240
