### ISSUE TITLE
Ask user to confirm before deleting an item from CSS Variables

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#53]
Moved from https://github.com/Starcounter/CssVariablesManager/issues/22

@Mihaiii wrote:

> Right now, deleting an item requires one click. A confirmation should be needed before an item is deleted as suggested [here](https://github.com/StarcounterApps/CssVariablesManager/pull/20#pullrequestreview-49479277) .

**Comment by PatrykSzwer** [comment]
@kegor please take this one. It should be fairly easy and complicated at the same time for You.

**Comment by kegor** [comment]
Closed as fixed in #56.

**Comment by warpech** [comment]
Setting as “Finished” because it is:
- released (with release notes) https://github.com/Starcounter/Blending/releases/tag/5.2.0
- published in the App Warehouse
