### ISSUE TITLE
Add automatic tests for BlendingEditor UI

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#55]
Most of the upcoming problems and undiscovered issues cames from bugs in BlendingEditor UI which came up from some SC/CE updates or changes that We didn't expect or know to change anything in that matter. 
Solution for that are automatic tests for app UI, similarly like those done in Kitchensink. We should have at least one automatic test for each our main functionality, along with navigation and others.

**Comment by kegor** [comment]
Closed because #62 was merged.
