### ISSUE TITLE
Collection details page warning about empty collection is not working

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#64]
Warning is displayed all the time, even when there are some variables:
![image](https://user-images.githubusercontent.com/25042256/35555634-19b8452c-05a0-11e8-8976-c3e5f1035307.png)

**Comment by PatrykSzwer** [comment]
This issue was fixed in commit https://github.com/Starcounter/Blending/commit/94c5c021d6cf8d43a5ee002605b3690ba1734840. After PR that contains it will be merged to `master` branch I'll close this issue.

**Comment by warpech** [comment]
Closing as fixed
