### ISSUE TITLE
Apply the new jargon

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#65]
Since we have now agreed on the new jargon (https://github.com/Starcounter/RebelsLounge/issues/227#issuecomment-361909655), the following names in BlendingEditor should be replaced:

- Surface → Layout
- Routes → Layout conditions
- Blending point → Area
- Blending rule → Area items

@kegor could you please do that in:

- UI
- app logic (view-models, etc)
- URIs
- README.md

-----

I suggest to base the work on https://github.com/Starcounter/Blending/pull/62 branch.

**Comment by kegor** [comment]
Closed because (I hope) mostly the all renamings were performed and merged in #66.
