### ISSUE TITLE
The tests do not pass with Starcounter newer than 2.4.0.4692

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#67]
I discovered this with the branch of PR https://github.com/Starcounter/Blending/pull/62 (`55-add-automatic-tests`), but I suppose that the `master` branch is equally affected.

The app is tested successfully on TeamCity with Starcounter 2.4.0.4692. Any version of Statcounter newer than that causes from 4 to 6 tests to fail:

```	
WebStuffDisablingTests(Chrome,DisableViewKeeper).ReenableDuplicatedBlendingRule_ThisRuleContentNotLoaded  	
WebStuffDisablingTests(Chrome,EnableViewKeeper).ReenableDuplicatedBlendingRule_ThisRuleContentNotLoaded  	
WebStuffDisablingTests(Firefox,DisableViewKeeper).ReenableDuplicatedBlendingRule_ThisRuleContentNotLoaded  	
WebStuffDisablingTests(Firefox,EnableViewKeeper).ReenableDuplicatedBlendingRule_ThisRuleContentNotLoaded 
```

@PatrykSzwer, @kegor please investigate what might be the reason?

**Comment by PatrykSzwer** [comment]
It seems like some one-version issue, because either locally and teamcity there are no more failing tests.

**Comment by kegor** [comment]
Closed because the fix was merged in #68.

**Comment by warpech** [comment]
Is there any good explanation why did it start to fail only recently?

**Comment by PatrykSzwer** [comment]
We talked a little with Anton about it and We came up with only 2 possibilities: 
1. It can be a coincidence that It appeared just now.
2. There had to be some low-level change in obtaining data that triggered this issue to bubble up.
