### ISSUE TITLE
RequestEmptyJson_ResponseNowWrapped test for BlendingProvider is flaky

### ISSUE THREAD

**Issue by kegor** [Starcounter/Blending#70]
This issue was initially met in #62.

### Steps to reproduce
Run build on TC with latest Blending master branch and latest SC 2.4.

### Expected result
All tests are green.

### Actual result
BlendingProvider.Tests.RequestEmptyJson_ResponseNowWrapped can be failed.

##### Starcounter version
2.4.0.4903

##### Involved apps' version
 - BlendingProvider@5.2.0
 
##### Browsers affected
- [x] Firefox

### Screenshot
_The bug itself:_
![image](https://user-images.githubusercontent.com/17431807/35911815-eeb40b1e-0c0b-11e8-9101-f953a19a0a22.png)

_Chrome can render empty curly braces in HTML body:_
![image](https://user-images.githubusercontent.com/17431807/35911846-0584787e-0c0c-11e8-8121-31c1813b7c0e.png) 

_And Firefox can't, this looks like root cause (but why most of the times this test passed on TC?):_
![image](https://user-images.githubusercontent.com/17431807/35911850-0afc9e08-0c0c-11e8-974f-25e4a52fcb33.png)

**Comment by warpech** [comment]
I will investigate this.

**Comment by warpech** [comment]
On TeamCity, this test has a success ratio o 94%: https://teamcity.starcounter.org/project.html?projectId=Apps_Blending&testNameId=-1473417678188584476&tab=testDetails

Last failure was on 2018-02-20. 

@kegor do you know how to reproduce this?

**Comment by kegor** [comment]
No, I simply saw that it several times failed in TC in the past.

**Comment by warpech** [comment]
I will close this then for the time being. Let's investigate flaky tests when TeamCity detects some: https://teamcity.starcounter.org/project.html?projectId=Apps_Blending&tab=flakyTests&branch_Apps_Blending=%3Cdefault%3E

I think that right now it has too little information.
