### ISSUE TITLE
Make a page about composition editor

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#75]
As discussed on the today's meeting, add a new page "Composition Editor" to the menu.

This page should have the following static content for the beginning:

> # COMPOSITION EDITOR
>
> Composition editor is a feature of BlendingEditor allowing you to create and manage custom compositions of partial HTML views coming from blended apps.
>
> To open the composition editor, press `CTRL`+`E` on any page. The editor will open on the top of the screen.
>
> For more information about using the composition editor, see the docs: https://docs.starcounter.io/guides/web-apps/view-composing

Is this enough for the beginning? In future we can make changes to this page as separate PRs.

@kegor please start the work from the PR #63 and add @PatrykSzwer as the reviewer.

**Comment by kegor** [comment]
Closed because the fix was merged in #78.
