### ISSUE TITLE
Links to the guidelines in CONTRIBUTING.md are not working

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#77]
By going to https://github.com/Starcounter/Blending/blob/master/CONTRIBUTING.md and clicking links like: 
>To contribute code to this repository, follow the instructions in the [guidelines](https://starcounter.gitbooks.io/guidelines/content/contributing-code.html).

You will get `Page not found` error. We should replace those with updated links/descriptions.

**Comment by warpech** [comment]
Please change to:

- https://github.com/Starcounter/CompanyTrack/blob/master/AppsTeam/Guidelines/version_control/contributing_code.md
- https://github.com/Starcounter/CompanyTrack/blob/master/AppsTeam/Guidelines/releasing-to-warehouse.md

These pages are not always up to date, but give a rough idea of what is expected.

**Comment by kegor** [comment]
Closed because fixes were merged in #82.
