### ISSUE TITLE
Restore blendingEditor tests in teamcity build when we are ready

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#83]
In teamcity configuration parameters:
![image](https://user-images.githubusercontent.com/25042256/36316200-fe0d49c4-1339-11e8-89bf-d4d2a68f15d3.png)
I removed parts about blendingEditor tests. We don't want them now due to complex changes for blendingEditor layout, but those should be restored when We fix tests for new layout.

**Comment by kegor** [comment]
Closed because the fix was merged in the #84.
