### ISSUE TITLE
🤸 Select CSS variable collections to be provided with a layout

### ISSUE THREAD

**Issue by warpech** [Starcounter/Blending#88]
Currently, it is possible to define CSS variable collections in BlendingEditor, but to use them in a layout, you need to explicitly put the URI of the collection as an area item.

## Selecting the collections

To make this easier, we should add a possibility to select the CSS variable collection on the "General" page of a layout.

I imagine it like this:

> ![image](https://user-images.githubusercontent.com/566463/36494084-698425a6-1731-11e8-93cb-8c4d40eb80c7.png)

When you press the <kbd>Select collections</kbd> button, a modal opens with a checkbox containing the list of available CSS variable collections. You can select more than one.

## Providing the collections

For all selected collections, BlendingProvider should include that collection in the light DOM part of [layout view HTML handler](https://github.com/Starcounter/Blending/blob/6daec49cfaf6e10bd21e7451bb71a629ae4f264d/src/BlendingProvider/Website/Api/ContentHandlers.cs#L63-L89)

@PatrykSzwer, @kegor WDYT?

**Comment by kegor** [comment]
In general, this sounds more UX friendly.

**Comment by PatrykSzwer** [comment]
I definitely agree. Since we have CssVariablesManager merged to blending it should be relatively easy to do.

**Comment by warpech** [comment]
Great! @PatrykSzwer can you pls work on that next week then?

**Comment by PatrykSzwer** [comment]
Closing as done.
