### ISSUE TITLE
starcounter-layout-html-editor should not be imported until it's need

### ISSUE THREAD

**Issue by tomalec** [Starcounter/Blending#95]
Currently, as you can see https://github.com/Starcounter/Blending/blob/master/src/BlendingEditor/wwwroot/BlendingEditor/elements/compositioneditor-panel/compositioneditor-panel.html#L1

When Blending app is running, every partial import `compositioneditor-panel.html` there fore `starcounter-layout-html-editor` which includes heavy elements like Ace editor etc

It affects performance https://github.com/Starcounter/RebelsLounge/issues/225 by sending 8 requests, in 50ms when served even from local machine.

### Steps to reproduce
1. Run any app and Blending,
2. Open any page,
3. Inspect network tab

### Expected result
`starcounter-layout-html-editor.html` and its dependencies should not be loaded until needed.
Requested, or preloaded.

### Actual result
`starcounter-layout-html-editor.html` is imported on first page load as one of the firsts in cascade.

##### Browsers affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari

### Screenshot
![obraz](https://user-images.githubusercontent.com/17435/36690747-8c89820c-1b33-11e8-88cc-a3197a80914a.png)

![obraz](https://user-images.githubusercontent.com/17435/36690787-b1014318-1b33-11e8-92ab-abeab8be9817.png)

**Comment by warpech** [comment]
@tomalec will work on this.

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/Blending/issues/23

**Comment by tomalec** [comment]
Closing as done in https://github.com/Starcounter/Blending/pull/196
