### ISSUE TITLE
Layout group select is empty when there is only one group

### ISSUE THREAD

**Issue by PatrykSzwer** [Starcounter/Blending#99]
![image](https://user-images.githubusercontent.com/25042256/36785988-12db3d44-1c85-11e8-868c-f66892787063.png)

**Comment by kegor** [comment]
As I can see this might be the common problem for all `juicy-select` components:
![image](https://user-images.githubusercontent.com/17431807/36886989-0a2cc72c-1e00-11e8-8311-b4b35b76bd07.png)
@PatrykSzwer am I right that we should see in these inputs values of the `caption-text` attributes, for example `Ungrouped` for the first one and `None` for the second?

**Comment by PatrykSzwer** [comment]
According to https://github.com/Juicy/juicy-select#properties section:
`Text of an empty option, empty option will not be created if the value is not set`

**Comment by alshakero** [comment]
I checked and `options` array is actually empty. Why do you expect `juicy-select` to list anything?

**Comment by kegor** [comment]
Guys, I also got an idea, I think we can remove the check for `this.options.length` in the following line: https://github.com/Juicy/juicy-select/blob/84274eebb24361396c2da7d3c89989be1af9488f/juicy-select.html#L50 because in the opposite case we will never see the empty option with `caption text`.

@PatrykSzwer, @alshakero wdyt?

**Comment by alshakero** [comment]
@kegor that's neat. I tried it locally and it works! I'll PR to `juicy-select` soon.

**Comment by alshakero** [comment]
Created https://github.com/Juicy/juicy-select/pull/20

**Comment by kegor** [comment]
@PatrykSzwer I think that current bug could be closed after PR from Omar will be merged. Wdyt?

**Comment by warpech** [comment]
This bug can be closed when a new version of `juicy-select` is released and installed in BlendingEditor.

**Comment by alshakero** [comment]
Heads up: [`juicy-select` is released]( https://github.com/Juicy/juicy-select/releases/tag/1.1.3).

**Comment by kegor** [comment]
Closed because the fix for `juicy-select` was merged into BlendingEditor in #110.
